# Generated by Django 4.0 on 2021-12-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('floor', models.IntegerField()),
                ('apt_num', models.CharField(max_length=200)),
                ('complant', models.TextField()),
                ('cateogry', models.CharField(choices=[('Plumbing', 'PL'), ('Electrical', 'EL'), ('Maintenance', 'MT'), ('CUSTODIAL', 'CAS')], max_length=50)),
            ],
        ),
    ]
