# Generated by Django 4.0 on 2022-01-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_reportdata_cateogry'),
    ]

    operations = [
        migrations.CreateModel(
            name='employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.AlterModelOptions(
            name='reportdata',
            options={'verbose_name_plural': 'Work Orders'},
        ),
    ]
