# Generated by Django 4.0 on 2022-01-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_orders_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='cateogry',
            field=models.CharField(choices=[('PL', 'Plumbing'), ('EL', 'Electrical'), ('MT', 'Maintenance'), ('CAS', 'CUSTODIAL'), ('ENG', 'Engineering'), ('EXT', 'Exterminator')], max_length=50),
        ),
    ]
