# Generated by Django 4.0 on 2022-01-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_reportdata_cateogry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employess',
        ),
    ]
